export enum Pet {
    EmptyPet = "pet_EmptyPet",
    Alien = "pet_Alien",
    Crewmate = "pet_Crewmate",
    Doggy = "pet_Doggy",
    Stickmin = "pet_Stickmin",
    Hamster = "pet_Hamster",
    Robot = "pet_Robot",
    UFO = "pet_UFO",
    Ellie = "pet_Ellie",
    Squig = "pet_Squig",
    Bedcrab = "pet_Bedcrab",
    Test = "pet_test",
    Lava = "pet_Lava",
    Snow = "pet_Snow",
    Charles = "pet_Charles",
    CharlesRed = "pet_Charles_Red",
    Cube = "pet_Cube",
    Bush = "pet_Bush",
    Frankendog = "pet_frankendog",
    Poro = "pet_poro"
}