export enum RoleType {
    Crewmate,
    Impostor,
    Scientist,
    Engineer,
    GuardianAngel,
    Shapeshifter,
    CrewmateGhost,
    ImpostorGhost,
    Noisemaker,
    Phantom,
    Tracker,
    Detective = 12,
    Viper = 18,
}
