export enum RpcMessageTag {
    PlayAnimation,
    CompleteTask,
    SyncSettings,
    SetInfected,
    Exiled,
    CheckName,
    SetName,
    CheckColor,
    SetColor,
    ReportDeadBody = 11,
    MurderPlayer,
    SendChat,
    StartMeeting,
    SetScanner,
    SendChatNote,
    SetStartCounter = 18,
    EnterVent,
    ExitVent,
    SnapTo,
    Close,
    VotingComplete,
    CastVote,
    ClearVote,
    AddVote,
    CloseDoorsOfType,
    RepairSystem,
    SetTasks,
    ClimbLadder = 31,
    UsePlatform,
    SendQuickChat,
    BootFromVent,
    UpdateSystem,
    SetLevel = 38,
    SetHat,
    SetSkin,
    SetPet,
    SetVisor,
    SetNameplate,
    SetRole,
    ProtectPlayer,
    Shapeshift,
    CheckMurder,
    CheckProtect,
    Pet,
    CancelPet,
    CheckZipline,
    TriggerSpores,
    CheckSpore,
    CheckShapeshift,
    RejectShapeshift,
    LobbyTimeExpiring = 60,
    ExtendLobbyTimer,
    CheckVanish,
    StartVanish,
    CheckAppear,
    StartAppear,
}
