export enum Filters {
    Tags,
    PlayerSpeed,
    Roles,
    KillCooldown,
    VotingTime,
    NumImposters,
    VisualTasks,
    AnonymousVotes,
    ConfirmEjects,
    DiscussionTime,
    EmergencyCooldown,
    NumEmergencyMeetings,
    NumCommonTasks,
    NumShortTasks,
    NumLongTasks,
    KillDistance,
}
