export enum TheSkeldVent {
    Admin,
    RightHallway,
    Cafeteria,
    Electrical,
    UpperEngine,
    Security,
    MedBay,
    Weapons,
    LowerReactor,
    LowerEngine,
    Shields,
    UpperReactor,
    UpperNavigation,
    LowerNavigation,
}
